### ISSUE TITLE
As a script developer, I want to create a script for combining multiple CSV files.

### ISSUE THREAD

**Issue by buttimec** [Subsss1/Sweng-project#8]
These CSV files were previosuly pcap files of network flows converted to CSV files

**Comment by ayndqy** [comment]
I would suggest changing the purpose of this issue. Merging multiple PCAPs is unnecessary complicated, so it's better to first convert them to CSVs and then merge those CSVs, rather than merging PCAPs.

**Comment by buttimec** [comment]
This requirement turned out to be redundant and not useful to the project. So alternative decisions and implementations were made.
